CREATE TABLE `con4data` ( `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'Game ID' , 
`GAMEDATA` VARCHAR(42) NOT NULL DEFAULT 'NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN' COMMENT 'Current Board data' , 
`LASTPLAYED` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
`TURN` ENUM('BLUE','RED') NOT NULL DEFAULT 'BLUE' COMMENT 'The player to move next' , 
`WINNER` ENUM('BLUE','RED','NONE') NOT NULL DEFAULT 'NONE' COMMENT 'The winner of the game. Not currently used' , 
`p2joined` BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'Whether a second player has EVER joined this game ID' , PRIMARY KEY (`ID`));
